/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Excepciones.*;
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import practica1_ejercicio1.Controlador;

/**
 *
 * @author 1GDAW07
 */
public class Vinsertar extends javax.swing.JDialog {
private String nombre;
private int edad;
private String profesion;
private int telefono;
    /**
     * Creates new form Vinsertar
     */
    public Vinsertar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Bsalir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Baceptar = new javax.swing.JButton();
        TFnombre = new javax.swing.JTextField();
        TFedad = new javax.swing.JTextField();
        TFprofesion = new javax.swing.JTextField();
        TFtelefono = new javax.swing.JTextField();
        Bsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Insertar Persona");

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Profeison");

        jLabel5.setText("Telefono");

        Baceptar.setText("Aceptar");
        Baceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaceptarActionPerformed(evt);
            }
        });

        TFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnombreActionPerformed(evt);
            }
        });

        TFedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFedadActionPerformed(evt);
            }
        });

        TFprofesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFprofesionActionPerformed(evt);
            }
        });

        TFtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtelefonoActionPerformed(evt);
            }
        });

        Bsalir.setText("Salir");
        Bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFprofesion, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(TFedad, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFnombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Baceptar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Bsalir)))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TFedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TFprofesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(TFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(Baceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bsalir)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnombreActionPerformed
        try{
                if(TFnombre.getText().isEmpty()){
                    throw new Llenar();
                 }
                else
                    if(TFnombre.getText().length()<2){
                        throw new DatoNoValido("Nombre Demasiado Corto");
                    }
                    else{
                        Pattern patron=Pattern.compile("^[A-Z][a-z]$");
                        Matcher m=patron.matcher(TFnombre.getText());
                        if(m.matches())
                            throw new DatoNoValido("El nombre tiene que ser de letras");
                        else
                            nombre=TFnombre.getText();
                            TFedad.requestFocus();
                    }
                        
            }
        catch(Llenar e){
            JOptionPane.showMessageDialog(this,"El campo esta vacio");
        }
        catch(DatoNoValido e){
             JOptionPane.showMessageDialog(this,e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage()+e.getClass());
        }
    }//GEN-LAST:event_TFnombreActionPerformed

    private void TFedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFedadActionPerformed
       try{
           if(TFedad.getText().isEmpty()){
               throw new Llenar();
           }
           else
               if(TFedad.getText().length()>=3){
                   throw new DatoNoValido("La edad tiene que ser 1 o 2 numeros");
               }
               else{
                   Pattern patron=Pattern.compile("^[0-9]$");
                   Matcher m=patron.matcher(TFedad.getText());
                   if(m.matches())
                       throw new DatoNoValido("La edad tiene que ser en numeros");
                   else
                       edad=Integer.parseInt(TFedad.getText());
                       TFprofesion.requestFocus();
               }
       }
       catch(Llenar e){
           JOptionPane.showMessageDialog(this,"El campo esta vacio");
       }
       catch(DatoNoValido e){
           JOptionPane.showMessageDialog(this,e.getMessage());
       }
       catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage()+e.getClass());
       }
    }//GEN-LAST:event_TFedadActionPerformed

    private void TFprofesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFprofesionActionPerformed
        try{
            if(TFprofesion.getText().isEmpty()){
                throw new Llenar();
            }
            else
                if(TFprofesion.getText().length()<5){
                    throw new DatoNoValido("La profesion es demasiado corta");
                }
                else{
                    Pattern patron=Pattern.compile("^[A-Z][a-z]$");
                    Matcher m=patron.matcher(TFprofesion.getText());
                    if(m.matches())
                        throw new DatoNoValido("La profesion tienen que ser palabras");
                    else
                        profesion=TFprofesion.getText();
                        TFtelefono.requestFocus();
                }
        }
        catch(Llenar e){
             JOptionPane.showMessageDialog(this,"El campo esta vacio");
        }
        catch(DatoNoValido e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(this,e.getMessage()+e.getClass());
        }
    }//GEN-LAST:event_TFprofesionActionPerformed

    private void TFtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtelefonoActionPerformed
        try{
            if(TFtelefono.getText().isEmpty())
                throw new Llenar();
            else
                if(TFtelefono.getText().length()!=9)
                    throw new DatoNoValido("El telefono son 9 numeros");
                else{
                    Pattern patron=Pattern.compile("^[0-9]{9}$");
                    Matcher m=patron.matcher(TFtelefono.getText());
                    if(!m.matches())
                        throw new DatoNoValido("El telefono tienen que ser numeros");
                    else
                        telefono=Integer.parseInt(TFtelefono.getText());
                }
                    
        }
        catch(Llenar e){
            JOptionPane.showMessageDialog(this,"El campo esta vacio");
        }
        catch(DatoNoValido e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage()+e.getClass());
        }
    }//GEN-LAST:event_TFtelefonoActionPerformed

    private void BaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaceptarActionPerformed
       try{
        Controlador.Registro(nombre,edad,profesion,telefono);
        JOptionPane.showMessageDialog(this,"Persona registrada correctamente");
        Bsalir.setVisible(true);
        
       }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage()+e.getClass());
        }
    }//GEN-LAST:event_BaceptarActionPerformed

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
       TFnombre.setText("");
       TFedad.setText("");
       TFprofesion.setText("");
       TFtelefono.setText("");
       Bsalir.setVisible(false);
        String n="vi";
        Controlador.Volver(n);
    }//GEN-LAST:event_BsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vinsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vinsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vinsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vinsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Vinsertar dialog = new Vinsertar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Baceptar;
    private javax.swing.JButton Bsalir;
    private javax.swing.JTextField TFedad;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JTextField TFprofesion;
    private javax.swing.JTextField TFtelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
