/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Usuarios;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import practica5.Controlador;

/**
 *
 * @author Alaitzutzu
 */
public class VAlta extends javax.swing.JFrame {
private String dni;
private int nss;
private String nombre;
private String apellidos;
private int telefono;
private String sexo;
private String estado;
private String tipoContrato;
private int departamento;
private LocalDate fechaAlta;
private int numempleado;
private String dir;

    /**
     * Creates new form VAlta
     */
    public VAlta() {
        initComponents();
        setLocationRelativeTo(null);
        Controlador.TipoContrato(CBtipoContrato);
        Controlador.Departamento(CBdepartamento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGsexo = new javax.swing.ButtonGroup();
        BGestado = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FTXdni = new javax.swing.JFormattedTextField();
        FTXfechaAlta = new javax.swing.JFormattedTextField();
        TFnombre = new javax.swing.JTextField();
        TFdir = new javax.swing.JTextField();
        TFtelefono = new javax.swing.JTextField();
        TFnumEmple = new javax.swing.JTextField();
        RBsoltero = new javax.swing.JRadioButton();
        RBcasado = new javax.swing.JRadioButton();
        RBfemenino = new javax.swing.JRadioButton();
        RBmasculino = new javax.swing.JRadioButton();
        TFnss = new javax.swing.JTextField();
        Baceptar = new javax.swing.JButton();
        CBtipoContrato = new javax.swing.JComboBox<>();
        CBdepartamento = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        TFapellido = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DNI");

        jLabel2.setText("NSS");

        jLabel3.setText("Nombre ");

        jLabel4.setText("Dirección");

        jLabel5.setText("Teléfono");

        jLabel6.setText("Sexo");

        jLabel7.setText("Estado Civil");

        jLabel8.setText("Tipo de contrato");

        jLabel9.setText("Departamento");

        jLabel10.setText("Fecha de Alta");

        jLabel11.setText("Numero de Empleado");

        try {
            FTXdni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.##.##-U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FTXdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTXdniActionPerformed(evt);
            }
        });

        try {
            FTXfechaAlta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        TFdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFdirActionPerformed(evt);
            }
        });

        TFtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtelefonoActionPerformed(evt);
            }
        });

        TFnumEmple.setEditable(false);
        TFnumEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnumEmpleActionPerformed(evt);
            }
        });

        BGestado.add(RBsoltero);
        RBsoltero.setText("Solter@");
        RBsoltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBsolteroActionPerformed(evt);
            }
        });

        BGestado.add(RBcasado);
        RBcasado.setText("Casad@");
        RBcasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBcasadoActionPerformed(evt);
            }
        });

        BGsexo.add(RBfemenino);
        RBfemenino.setText("Femenino");
        RBfemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBfemeninoActionPerformed(evt);
            }
        });

        BGsexo.add(RBmasculino);
        RBmasculino.setText("Masculino");
        RBmasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBmasculinoActionPerformed(evt);
            }
        });

        TFnss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnssActionPerformed(evt);
            }
        });

        Baceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Baceptar.setText("Aceptar");
        Baceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaceptarActionPerformed(evt);
            }
        });

        CBtipoContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--" }));
        CBtipoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBtipoContratoActionPerformed(evt);
            }
        });

        CBdepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--" }));
        CBdepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBdepartamentoActionPerformed(evt);
            }
        });

        jLabel12.setText("Apellidos");

        TFapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFapellidoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel13.setText("ALTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFnss, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FTXdni, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TFapellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                        .addComponent(TFdir, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFnumEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FTXfechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBtipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RBsoltero)
                                    .addComponent(RBfemenino))))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RBcasado)
                            .addComponent(RBmasculino)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(Baceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel13)
                        .addGap(48, 48, 48)
                        .addComponent(FTXdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFnss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel11)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBfemenino)
                            .addComponent(RBmasculino))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBcasado)
                            .addComponent(RBsoltero, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBtipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FTXfechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFnumEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Baceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FTXdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTXdniActionPerformed
        dni=FTXdni.getText();
        TFnss.requestFocus();
        
    }//GEN-LAST:event_FTXdniActionPerformed

    private void TFnssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnssActionPerformed
        nss=Integer.parseInt(TFnss.getText());
        TFnombre.requestFocus();
        
    }//GEN-LAST:event_TFnssActionPerformed

    private void TFapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFapellidoActionPerformed
        apellidos=TFapellido.getText();
        TFdir.requestFocus();
        
    }//GEN-LAST:event_TFapellidoActionPerformed

    private void TFtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtelefonoActionPerformed
        telefono=Integer.parseInt(TFtelefono.getText());
       
    }//GEN-LAST:event_TFtelefonoActionPerformed

    private void RBfemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBfemeninoActionPerformed
        sexo="F";
    }//GEN-LAST:event_RBfemeninoActionPerformed

    private void RBmasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBmasculinoActionPerformed
        sexo="M";
    }//GEN-LAST:event_RBmasculinoActionPerformed

    private void RBsolteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBsolteroActionPerformed
       estado="soltero";
    }//GEN-LAST:event_RBsolteroActionPerformed

    private void RBcasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBcasadoActionPerformed
       estado="casado";
    }//GEN-LAST:event_RBcasadoActionPerformed

    private void CBtipoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBtipoContratoActionPerformed
       tipoContrato=CBtipoContrato.getItemAt(0);
    }//GEN-LAST:event_CBtipoContratoActionPerformed

    private void CBdepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBdepartamentoActionPerformed
        departamento=Integer.parseInt(CBdepartamento.getItemAt(0));
       FTXfechaAlta.requestFocus();
    }//GEN-LAST:event_CBdepartamentoActionPerformed

    private void TFnumEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnumEmpleActionPerformed
       boolean s=true;
       int n=0,num=0;
       for(int x=0;x<4;x++){
            n=(int)(Math.random()*100);
            num+=n;
       }
       s=Controlador.Numemple(n);

        if(s==true){
           numempleado=num;
           TFnumEmple.setText(Integer.toString(n));
       }
        else{
            do{
            num=0;
            n=(int)(Math.random()*100);
            num+=n;
            s=Controlador.Numemple(n);
            }
            while(s==false);
        }
    }//GEN-LAST:event_TFnumEmpleActionPerformed

    private void BaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaceptarActionPerformed
     boolean a=true;
    a=Controlador.TenDatos(dni,nss,nombre,apellidos,telefono,sexo,estado,tipoContrato,departamento,fechaAlta, numempleado,dir);
     if(a==true){
         JOptionPane.showMessageDialog(this,"La persona se ha dado de alta");
         if(departamento==1){
             Usuarios u=new Usuarios();
             u=Controlador.CrearUsuario();
             String us=u.getUsuario();
             String co=u.getContraseña();
             JOptionPane.showMessageDialog(this,"El usuario es: "+ us +"\n"
                     + "Y la contraseña es "+co);
         }
     }
     else{
         JOptionPane.showMessageDialog(this,"Ha habido un error,intentalo de nuevo");
         TFnombre.setText(" ");
         TFapellido.setText(" ");
         TFnss.setText(" ");
         FTXdni.setText(" ");
         TFtelefono.setText(" ");
         RBfemenino.setSelected(false);
         RBmasculino.setSelected(false);
         RBsoltero.setSelected(false);
         RBcasado.setSelected(false);
         CBtipoContrato.setSelectedIndex(0);
         CBdepartamento.setSelectedIndex(0);
         FTXfechaAlta.setText(" ");
         TFnombre.requestFocus();
     }
     Controlador.AceptarAlta();


    }//GEN-LAST:event_BaceptarActionPerformed

    private void TFdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFdirActionPerformed
        dir=TFdir.getText();
        TFtelefono.requestFocus();
    }//GEN-LAST:event_TFdirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAlta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGestado;
    private javax.swing.ButtonGroup BGsexo;
    private javax.swing.JButton Baceptar;
    private javax.swing.JComboBox<String> CBdepartamento;
    private javax.swing.JComboBox<String> CBtipoContrato;
    private javax.swing.JFormattedTextField FTXdni;
    private javax.swing.JFormattedTextField FTXfechaAlta;
    private javax.swing.JRadioButton RBcasado;
    private javax.swing.JRadioButton RBfemenino;
    private javax.swing.JRadioButton RBmasculino;
    private javax.swing.JRadioButton RBsoltero;
    private javax.swing.JTextField TFapellido;
    private javax.swing.JTextField TFdir;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JTextField TFnss;
    private javax.swing.JTextField TFnumEmple;
    private javax.swing.JTextField TFtelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
