/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import practica5.Controlador;

/**
 *
 * @author Alaitzutzu
 */
public class Vinicio extends javax.swing.JFrame {
private VAlta va=new VAlta();
private VBaja vb =new VBaja(this,true);
private VModificacion vm=new VModificacion(this,true);
private VListado vl= new VListado(this,true);
    /**
     * Creates new form Vinicio
     */
    public Vinicio() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MPersona = new javax.swing.JMenu();
        MIAlta = new javax.swing.JMenuItem();
        MIBaja = new javax.swing.JMenuItem();
        MIModificar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MInumEmple = new javax.swing.JMenuItem();
        MIContrrato = new javax.swing.JMenuItem();
        MIdepartamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MISalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("BIENVENID@");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Indica la operación que desee realizar");

        MPersona.setText("Personas");

        MIAlta.setText("Alta");
        MIAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIAltaActionPerformed(evt);
            }
        });
        MPersona.add(MIAlta);

        MIBaja.setText("Baja");
        MIBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIBajaActionPerformed(evt);
            }
        });
        MPersona.add(MIBaja);

        MIModificar.setText("Modificar");
        MIModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIModificarActionPerformed(evt);
            }
        });
        MPersona.add(MIModificar);

        jMenu1.setText("Listado");

        MInumEmple.setText("Por numero de empleado");
        MInumEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MInumEmpleActionPerformed(evt);
            }
        });
        jMenu1.add(MInumEmple);

        MIContrrato.setText("Por Contrato");
        MIContrrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIContrratoActionPerformed(evt);
            }
        });
        jMenu1.add(MIContrrato);

        MIdepartamento.setText("Por Departamento");
        MIdepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIdepartamentoActionPerformed(evt);
            }
        });
        jMenu1.add(MIdepartamento);

        MPersona.add(jMenu1);

        jMenuBar1.add(MPersona);

        jMenu2.setText("Salir");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        MISalir.setText("Salir");
        jMenu2.add(MISalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel2)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MIAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIAltaActionPerformed
       va.setVisible(true);
    }//GEN-LAST:event_MIAltaActionPerformed

    private void MIBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIBajaActionPerformed
       vb.setVisible(true);
    }//GEN-LAST:event_MIBajaActionPerformed

    private void MIModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIModificarActionPerformed
         vm.setVisible(true);
    }//GEN-LAST:event_MIModificarActionPerformed

    private void MInumEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MInumEmpleActionPerformed
         vl.setVisible(true);
    }//GEN-LAST:event_MInumEmpleActionPerformed

    private void MIContrratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIContrratoActionPerformed
         vl.setVisible(true);
    }//GEN-LAST:event_MIContrratoActionPerformed

    private void MIdepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIdepartamentoActionPerformed
        vl.setVisible(true);
    }//GEN-LAST:event_MIdepartamentoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       Controlador.Salir();
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vinicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MIAlta;
    private javax.swing.JMenuItem MIBaja;
    private javax.swing.JMenuItem MIContrrato;
    private javax.swing.JMenuItem MIModificar;
    private javax.swing.JMenuItem MISalir;
    private javax.swing.JMenuItem MIdepartamento;
    private javax.swing.JMenuItem MInumEmple;
    private javax.swing.JMenu MPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
