/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Empleado;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import practica5.Controlador;

/**
 *
 * @author Alaitzutzu
 */
public class VModificacion extends javax.swing.JDialog {
private ArrayList <Empleado> ListaEmpleados=new ArrayList();
private ArrayList <Empleado> e=new ArrayList();
    /**
     * Creates new form VModificacion
     */
    public VModificacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        ListaEmpleados=Controlador.Empleados();
        lista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGempleados = new javax.swing.ButtonGroup();
        BGsexo = new javax.swing.ButtonGroup();
        BGestado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        RB = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB3 = new javax.swing.JRadioButton();
        RB4 = new javax.swing.JRadioButton();
        RB5 = new javax.swing.JRadioButton();
        RB6 = new javax.swing.JRadioButton();
        RB7 = new javax.swing.JRadioButton();
        RB8 = new javax.swing.JRadioButton();
        RB9 = new javax.swing.JRadioButton();
        RB10 = new javax.swing.JRadioButton();
        Pdatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RBf = new javax.swing.JRadioButton();
        RBm = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        RBcasado = new javax.swing.JRadioButton();
        RBsoltero = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CBtipoContrato = new javax.swing.JComboBox<>();
        CBdepartamento = new javax.swing.JComboBox<>();
        TFnumEmple = new javax.swing.JTextField();
        FTFfechaAlta = new javax.swing.JFormattedTextField();
        FTFdni = new javax.swing.JFormattedTextField();
        TFnss = new javax.swing.JTextField();
        TFnombre = new javax.swing.JTextField();
        TFapellido = new javax.swing.JTextField();
        TFdir = new javax.swing.JTextField();
        TFtelefono = new javax.swing.JTextField();
        BAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados"));

        BGempleados.add(RB);
        RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBActionPerformed(evt);
            }
        });

        BGempleados.add(RB2);
        RB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB2ActionPerformed(evt);
            }
        });

        BGempleados.add(RB3);
        RB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB3ActionPerformed(evt);
            }
        });

        BGempleados.add(RB4);
        RB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB4ActionPerformed(evt);
            }
        });

        BGempleados.add(RB5);
        RB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB5ActionPerformed(evt);
            }
        });

        BGempleados.add(RB6);
        RB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB6ActionPerformed(evt);
            }
        });

        BGempleados.add(RB7);
        RB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB7ActionPerformed(evt);
            }
        });

        BGempleados.add(RB8);
        RB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB8ActionPerformed(evt);
            }
        });

        BGempleados.add(RB9);
        RB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB9ActionPerformed(evt);
            }
        });

        BGempleados.add(RB10);
        RB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RB5)
                    .addComponent(RB4)
                    .addComponent(RB3)
                    .addComponent(RB2)
                    .addComponent(RB))
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RB6)
                    .addComponent(RB7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(RB8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(RB10))
                    .addComponent(RB9))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB)
                    .addComponent(RB6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB2)
                    .addComponent(RB7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RB3)
                            .addComponent(RB8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RB4))
                    .addComponent(RB9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB5)
                    .addComponent(RB10)))
        );

        Pdatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setText("DNI");

        jLabel2.setText("NSS");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Dirección");

        jLabel6.setText("Telefono");

        BGsexo.add(RBf);
        RBf.setText("Femenino");

        BGsexo.add(RBm);
        RBm.setText("Masculino");

        jLabel7.setText("Sexo");

        jLabel8.setText("Estado");

        BGestado.add(RBcasado);
        RBcasado.setText("Casad@");

        BGestado.add(RBsoltero);
        RBsoltero.setText("Solter@");

        jLabel9.setText("Tipo De contrato");

        jLabel10.setText("Departamento");

        jLabel11.setText("Fecha Alta");

        jLabel12.setText("NumEmple");

        CBtipoContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--" }));

        CBdepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--" }));

        TFnumEmple.setEditable(false);

        FTFfechaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFfechaAltaActionPerformed(evt);
            }
        });

        FTFdni.setEditable(false);
        FTFdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFdniActionPerformed(evt);
            }
        });

        TFnss.setEditable(false);
        TFnss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnssActionPerformed(evt);
            }
        });

        TFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnombreActionPerformed(evt);
            }
        });

        TFapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFapellidoActionPerformed(evt);
            }
        });

        TFdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFdirActionPerformed(evt);
            }
        });

        TFtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PdatosLayout = new javax.swing.GroupLayout(Pdatos);
        Pdatos.setLayout(PdatosLayout);
        PdatosLayout.setHorizontalGroup(
            PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PdatosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PdatosLayout.createSequentialGroup()
                        .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PdatosLayout.createSequentialGroup()
                                .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FTFdni, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(TFnss)))
                            .addGroup(PdatosLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(TFnumEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PdatosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(TFnombre))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PdatosLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(TFapellido))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PdatosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(TFdir))
                            .addGroup(PdatosLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(TFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PdatosLayout.createSequentialGroup()
                                .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PdatosLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(26, 26, 26)
                                        .addComponent(RBcasado))
                                    .addGroup(PdatosLayout.createSequentialGroup()
                                        .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(PdatosLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(26, 26, 26))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PdatosLayout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(RBf)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBm, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RBsoltero, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(PdatosLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(CBdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PdatosLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)
                                .addComponent(CBtipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PdatosLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(FTFfechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(780, 780, 780))))
        );
        PdatosLayout.setVerticalGroup(
            PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PdatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FTFdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFnss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PdatosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBf)
                            .addComponent(RBm)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(RBcasado)
                            .addComponent(RBsoltero))
                        .addGap(18, 18, 18)
                        .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(CBtipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(CBdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(FTFfechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TFnumEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(TFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        BAceptar.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(384, 384, 384)
                                .addComponent(BAceptar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Pdatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pdatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBActionPerformed
       e=Controlador.GetDatos(0);
    }//GEN-LAST:event_RBActionPerformed

    private void RB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB2ActionPerformed
         e=Controlador.GetDatos(1);
    }//GEN-LAST:event_RB2ActionPerformed

    private void RB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB3ActionPerformed
         e=Controlador.GetDatos(2);
    }//GEN-LAST:event_RB3ActionPerformed

    private void RB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB4ActionPerformed
         e=Controlador.GetDatos(3);
    }//GEN-LAST:event_RB4ActionPerformed

    private void RB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB5ActionPerformed
        e= Controlador.GetDatos(4);
    }//GEN-LAST:event_RB5ActionPerformed

    private void RB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB6ActionPerformed
       e=  Controlador.GetDatos(5);
    }//GEN-LAST:event_RB6ActionPerformed

    private void RB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB7ActionPerformed
        e=Controlador.GetDatos(6);
    }//GEN-LAST:event_RB7ActionPerformed

    private void RB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB8ActionPerformed
       e= Controlador.GetDatos(7);
    }//GEN-LAST:event_RB8ActionPerformed

    private void RB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB9ActionPerformed
       e= Controlador.GetDatos(8);
    }//GEN-LAST:event_RB9ActionPerformed

    private void RB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB10ActionPerformed
      e=  Controlador.GetDatos(9);
    }//GEN-LAST:event_RB10ActionPerformed

    private void FTFdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFdniActionPerformed
      FTFdni.setText(e.get(0).getDNI());
      
    }//GEN-LAST:event_FTFdniActionPerformed

    private void TFnssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnssActionPerformed
       TFnss.setText(Integer.toString(e.get(0).getNSS()));
    }//GEN-LAST:event_TFnssActionPerformed

    private void TFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnombreActionPerformed
       TFnombre.setText(e.get(0).getNombre());
       
    }//GEN-LAST:event_TFnombreActionPerformed

    private void TFapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFapellidoActionPerformed
        TFapellido.setText(e.get(0).getApellidos());
    }//GEN-LAST:event_TFapellidoActionPerformed

    private void TFdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFdirActionPerformed
       TFdir.setText(e.get(0).getDireccion());
    }//GEN-LAST:event_TFdirActionPerformed

    private void TFtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtelefonoActionPerformed
        TFtelefono.setText(Integer.toString(e.get(0).getTelefono()));
    }//GEN-LAST:event_TFtelefonoActionPerformed

    private void FTFfechaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFfechaAltaActionPerformed
        DateTimeFormatter formatter=DateTimeFormatter.ofPattern("dd/MM/yyyy");
        FTFfechaAlta.setText(LocalDate.parse(e.get(0).getFechaAlta(),formatter));
    }//GEN-LAST:event_FTFfechaAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void lista(){
          if(ListaEmpleados.size()==1){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setVisible(false);
             RB3.setVisible(false);
             RB4.setVisible(false);
             RB5.setVisible(false);
             RB6.setVisible(false);
             RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
        }
       if(ListaEmpleados.size()==2){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
              RB3.setVisible(false);
             RB4.setVisible(false);
             RB5.setVisible(false);
             RB6.setVisible(false);
             RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
        }
        if(ListaEmpleados.size()==3){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setVisible(false);
             RB5.setVisible(false);
             RB6.setVisible(false);
             RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);

        }
         if(ListaEmpleados.size()==4){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
              RB5.setVisible(false);
             RB6.setVisible(false);
             RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
         }
         if(ListaEmpleados.size()==5){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setVisible(false);
             RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
         }
         if(ListaEmpleados.size()==6){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setText(ListaEmpleados.get(5).getNombre());
                 RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
         }
          if(ListaEmpleados.size()==7){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setText(ListaEmpleados.get(5).getNombre());
                RB7.setText(ListaEmpleados.get(6).getNombre());
                RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
         }
          if(ListaEmpleados.size()==8){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setText(ListaEmpleados.get(5).getNombre());
                RB7.setText(ListaEmpleados.get(6).getNombre());
                RB8.setText(ListaEmpleados.get(7).getNombre());
                 RB9.setVisible(false);
              RB10.setVisible(false);
         }
          if(ListaEmpleados.size()==9){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setText(ListaEmpleados.get(5).getNombre());
                RB7.setText(ListaEmpleados.get(6).getNombre());
                  RB9.setText(ListaEmpleados.get(8).getNombre());
                  RB10.setVisible(false);
         }
          if(ListaEmpleados.size()==10){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setText(ListaEmpleados.get(5).getNombre());
                RB7.setText(ListaEmpleados.get(6).getNombre());
                  RB9.setText(ListaEmpleados.get(8).getNombre());
                   RB10.setText(ListaEmpleados.get(9).getNombre());
         }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VModificacion dialog = new VModificacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.ButtonGroup BGempleados;
    private javax.swing.ButtonGroup BGestado;
    private javax.swing.ButtonGroup BGsexo;
    private javax.swing.JComboBox<String> CBdepartamento;
    private javax.swing.JComboBox<String> CBtipoContrato;
    private javax.swing.JFormattedTextField FTFdni;
    private javax.swing.JFormattedTextField FTFfechaAlta;
    private javax.swing.JPanel Pdatos;
    private javax.swing.JRadioButton RB;
    private javax.swing.JRadioButton RB10;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JRadioButton RB4;
    private javax.swing.JRadioButton RB5;
    private javax.swing.JRadioButton RB6;
    private javax.swing.JRadioButton RB7;
    private javax.swing.JRadioButton RB8;
    private javax.swing.JRadioButton RB9;
    private javax.swing.JRadioButton RBcasado;
    private javax.swing.JRadioButton RBf;
    private javax.swing.JRadioButton RBm;
    private javax.swing.JRadioButton RBsoltero;
    private javax.swing.JTextField TFapellido;
    private javax.swing.JTextField TFdir;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JTextField TFnss;
    private javax.swing.JTextField TFnumEmple;
    private javax.swing.JTextField TFtelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
