/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Excepciones.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author 1GDAW07
 */
public class Valta extends javax.swing.JDialog {
private String nombre;
private String lugar;
private LocalDate fecha;
private LocalTime HoraInicio;
private LocalTime horaFin;
private int aforo;
    /**
     * Creates new form Vbaja
     */
    public Valta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Baceptar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Lnombre = new javax.swing.JLabel();
        Llugar = new javax.swing.JLabel();
        Lfecha = new javax.swing.JLabel();
        LhoraInicio = new javax.swing.JLabel();
        LhoraFin = new javax.swing.JLabel();
        Laforo = new javax.swing.JLabel();
        TFnombre = new javax.swing.JTextField();
        TFlugar = new javax.swing.JTextField();
        FTFhoraInicio = new javax.swing.JFormattedTextField();
        FTFhoraFin = new javax.swing.JFormattedTextField();
        TFaforo = new javax.swing.JTextField();
        FTFfecha = new javax.swing.JFormattedTextField();
        Baceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Alta");

        Lnombre.setText("Nombre");

        Llugar.setText("Lugar");

        Lfecha.setText("Fecha");

        LhoraInicio.setText("HoraInicio");

        LhoraFin.setText("HoraFin");

        Laforo.setText("Aforo");

        TFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnombreActionPerformed(evt);
            }
        });

        TFlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFlugarActionPerformed(evt);
            }
        });

        FTFhoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        FTFhoraInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFhoraInicioActionPerformed(evt);
            }
        });

        FTFhoraFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        FTFhoraFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFhoraFinActionPerformed(evt);
            }
        });

        TFaforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFaforoActionPerformed(evt);
            }
        });

        FTFfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        FTFfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFfechaActionPerformed(evt);
            }
        });

        Baceptar.setText("Aceptar");
        Baceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Llugar)
                                    .addGap(18, 18, 18)
                                    .addComponent(TFlugar))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Lnombre)
                                    .addGap(18, 18, 18)
                                    .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Laforo)
                                        .addComponent(LhoraFin))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(FTFhoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(TFaforo))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LhoraInicio)
                                    .addGap(18, 18, 18)
                                    .addComponent(FTFhoraInicio)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lfecha)
                                .addGap(16, 16, 16)
                                .addComponent(FTFfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(Baceptar)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnombre)
                    .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Llugar)
                    .addComponent(TFlugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lfecha)
                    .addComponent(FTFfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LhoraInicio)
                    .addComponent(FTFhoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LhoraFin)
                    .addComponent(FTFhoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Laforo)
                    .addComponent(TFaforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Baceptar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnombreActionPerformed
        try{
        if(TFnombre.getText().isEmpty())
            throw new Llenar("El campo nombre no puede estar vacio");
        else
            if(TFnombre.getText().length()<2)
                throw new DatoNoValido("El nombre tiene que tener más de dos cáracteres");
            else{
                Pattern patron=Pattern.compile("[A-Z][a-z]*");
                Matcher m=patron.matcher(TFnombre.getText());
                if(!m.matches())
                    throw new DatoNoValido("El nombre tiene que ser todo letras");
                else
                nombre=TFnombre.getText();
                TFlugar.requestFocus();
                }    
            }
        catch(Llenar e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        catch(DatoNoValido e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getClass()+e.getMessage());
        }
            
    }//GEN-LAST:event_TFnombreActionPerformed

    private void TFlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFlugarActionPerformed
        try{
            if(TFlugar.getText().isEmpty())
                throw new Llenar("El campo nombre no puede estar vacio");
            else
                if(TFlugar.getText().length()<3)
                    throw new DatoNoValido("Tiene que ser mas de tres cáracteres");
                else{
                    Pattern patron=Pattern.compile("[A-Z][a-z]*");
                    Matcher m=patron.matcher(TFlugar.getText());
                    if(!m.matches())
                        throw new DatoNoValido("Tiene que ser todo letras");
                    else
                        FTFfecha.requestFocus();
                        lugar=TFlugar.getText();
                }
        }
        catch(Llenar e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        catch(DatoNoValido e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getClass()+e.getMessage());
        }
    }//GEN-LAST:event_TFlugarActionPerformed

    private void FTFfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFfechaActionPerformed
         DateTimeFormatter f=DateTimeFormatter.ofPattern("dd/MM/yy");
        fecha=LocalDate.parse(FTFfecha.getText(),f);
         FTFhoraInicio.requestFocus();
       
    }//GEN-LAST:event_FTFfechaActionPerformed

    private void TFaforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFaforoActionPerformed
       try{
        if(TFaforo.getText().isEmpty())
           throw new Llenar("El aforo no puede estar vacio");
       else
           if(TFaforo.getText().length()<2)
               throw new DatoNoValido("El aforo tiene que ser mas de 10");
           else{
               Pattern patron=Pattern.compile("[0-9]{2,}");
               Matcher m=patron.matcher((TFaforo.getText()));
               if(!m.matches())
                   throw new DatoNoValido("El aforo tiene que ser numeros");
               else
               aforo=Integer.parseInt(TFaforo.getText());
               Baceptar.setVisible(true);
           }
               
        
       }
       catch(Llenar e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        catch(DatoNoValido e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getClass()+e.getMessage());
        }
    }//GEN-LAST:event_TFaforoActionPerformed

    private void FTFhoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFhoraInicioActionPerformed
   HoraInicio=LocalTime.parse(FTFhoraInicio.getText());
    FTFhoraFin.requestFocus();
    }//GEN-LAST:event_FTFhoraInicioActionPerformed

    private void FTFhoraFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFhoraFinActionPerformed
    horaFin=LocalTime.parse(FTFhoraFin.getText());
    TFaforo.requestFocus();
    }//GEN-LAST:event_FTFhoraFinActionPerformed

    private void BaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaceptarActionPerformed
        String n="va";
        boolean evento=true;
        evento=Controlador.Insertar(nombre,lugar,fecha,HoraInicio,horaFin,aforo);
        if(evento==true){
            JOptionPane.showMessageDialog(this,"El evento ha sido guardado correctamente");
            Controlador.Volver(n);
        }
        else{
            JOptionPane.showMessageDialog(this,"El evento no ha sido guardado correctamente");
            Controlador.Volver(n);
        }
    }//GEN-LAST:event_BaceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Valta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Valta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Valta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Valta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Valta dialog = new Valta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Baceptar;
    private javax.swing.JFormattedTextField FTFfecha;
    private javax.swing.JFormattedTextField FTFhoraFin;
    private javax.swing.JFormattedTextField FTFhoraInicio;
    private javax.swing.JLabel Laforo;
    private javax.swing.JLabel Lfecha;
    private javax.swing.JLabel LhoraFin;
    private javax.swing.JLabel LhoraInicio;
    private javax.swing.JLabel Llugar;
    private javax.swing.JLabel Lnombre;
    private javax.swing.JTextField TFaforo;
    private javax.swing.JTextField TFlugar;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
