/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Empleado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import practica5.Controlador;

/**
 *
 * @author Alaitzutzu
 */
public class VBaja extends javax.swing.JDialog {
private ArrayList <Empleado> ListaEmpleados=new ArrayList();
    /**
     * Creates new form VBaja
     */
    public VBaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        ListaEmpleados=Controlador.Empleados();
        ListarEmpleados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGempleado = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        RB = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB3 = new javax.swing.JRadioButton();
        RB4 = new javax.swing.JRadioButton();
        RB5 = new javax.swing.JRadioButton();
        RB6 = new javax.swing.JRadioButton();
        RB7 = new javax.swing.JRadioButton();
        RB8 = new javax.swing.JRadioButton();
        RB9 = new javax.swing.JRadioButton();
        RB10 = new javax.swing.JRadioButton();
        BAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("BAJA");

        BGempleado.add(RB);
        RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBActionPerformed(evt);
            }
        });

        BGempleado.add(RB2);
        RB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB2ActionPerformed(evt);
            }
        });

        BGempleado.add(RB3);
        RB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB3ActionPerformed(evt);
            }
        });

        BGempleado.add(RB4);
        RB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB4ActionPerformed(evt);
            }
        });

        BGempleado.add(RB5);
        RB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB5ActionPerformed(evt);
            }
        });

        BGempleado.add(RB6);
        RB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB6ActionPerformed(evt);
            }
        });

        BGempleado.add(RB7);
        RB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB7ActionPerformed(evt);
            }
        });

        BGempleado.add(RB8);
        RB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB8ActionPerformed(evt);
            }
        });

        BGempleado.add(RB9);
        RB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB9ActionPerformed(evt);
            }
        });

        BGempleado.add(RB10);
        RB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB10ActionPerformed(evt);
            }
        });

        BAceptar.setText("Aceptar");
        BAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RB2)
                            .addComponent(RB)
                            .addComponent(RB3)
                            .addComponent(RB4)
                            .addComponent(RB5)
                            .addComponent(RB6)
                            .addComponent(RB7)
                            .addComponent(RB8)
                            .addComponent(RB9)
                            .addComponent(RB10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(BAceptar)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RB9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RB10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(BAceptar)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceptarActionPerformed
       
    }//GEN-LAST:event_BAceptarActionPerformed

    private void RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBActionPerformed
        int p=0;
        boolean c=true;
        p=JOptionPane.showConfirmDialog(this,"Estas seguro que quieres dar de baja a "+ListaEmpleados.get(0).getNombre());
        if(p==0){
              c= Controlador.DarBaja(ListaEmpleados.get(0),0); 
              if(c==true){
                  JOptionPane.showMessageDialog(this,"El empleado se ha dado de baja ");
              }
            }
        
    }//GEN-LAST:event_RBActionPerformed

    private void RB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB2ActionPerformed
         int p=0;
        boolean c=true;
        p=JOptionPane.showConfirmDialog(this,"Estas seguro que quieres dar de baja a "+ListaEmpleados.get(1).getNombre());
        if(p==0){
              c= Controlador.DarBaja(ListaEmpleados.get(1),1); 
              if(c==true){
                  JOptionPane.showMessageDialog(this,"El empleado se ha dado de baja ");
              }
            }
    }//GEN-LAST:event_RB2ActionPerformed

    private void RB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB3ActionPerformed
       int p=0;
        boolean c=true;
        p=JOptionPane.showConfirmDialog(this,"Estas seguro que quieres dar de baja a "+ListaEmpleados.get(2).getNombre());
        if(p==0){
              c= Controlador.DarBaja(ListaEmpleados.get(2),2); 
              if(c==true){
                  JOptionPane.showMessageDialog(this,"El empleado se ha dado de baja ");
              }
            }
    }//GEN-LAST:event_RB3ActionPerformed

    private void RB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB4ActionPerformed
        int p=0;
        boolean c=true;
        p=JOptionPane.showConfirmDialog(this,"Estas seguro que quieres dar de baja a "+ListaEmpleados.get(3).getNombre());
        if(p==0){
              c= Controlador.DarBaja(ListaEmpleados.get(3),3); 
              if(c==true){
                  JOptionPane.showMessageDialog(this,"El empleado se ha dado de baja ");
              }
            }
    }//GEN-LAST:event_RB4ActionPerformed

    private void RB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB5ActionPerformed
         int p=0;
        boolean c=true;
        p=JOptionPane.showConfirmDialog(this,"Estas seguro que quieres dar de baja a "+ListaEmpleados.get(4).getNombre());
        if(p==0){
              c= Controlador.DarBaja(ListaEmpleados.get(4),4); 
              if(c==true){
                  JOptionPane.showMessageDialog(this,"El empleado se ha dado de baja ");
              }
            }
    }//GEN-LAST:event_RB5ActionPerformed

    private void RB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB6ActionPerformed
       int p=0;
        boolean c=true;
        p=JOptionPane.showConfirmDialog(this,"Estas seguro que quieres dar de baja a "+ListaEmpleados.get(5).getNombre());
        if(p==0){
              c= Controlador.DarBaja(ListaEmpleados.get(5),5); 
              if(c==true){
                  JOptionPane.showMessageDialog(this,"El empleado se ha dado de baja ");
              }
            }
    }//GEN-LAST:event_RB6ActionPerformed

    private void RB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB7ActionPerformed
         int p=0;
        boolean c=true;
        p=JOptionPane.showConfirmDialog(this,"Estas seguro que quieres dar de baja a "+ListaEmpleados.get(6).getNombre());
        if(p==0){
              c= Controlador.DarBaja(ListaEmpleados.get(6),6); 
              if(c==true){
                  JOptionPane.showMessageDialog(this,"El empleado se ha dado de baja ");
              }
            }
    }//GEN-LAST:event_RB7ActionPerformed

    private void RB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB8ActionPerformed
        int p=0;
        boolean c=true;
        p=JOptionPane.showConfirmDialog(this,"Estas seguro que quieres dar de baja a "+ListaEmpleados.get(7).getNombre());
        if(p==0){
              c= Controlador.DarBaja(ListaEmpleados.get(7),7); 
              if(c==true){
                  JOptionPane.showMessageDialog(this,"El empleado se ha dado de baja ");
              }
            }
    }//GEN-LAST:event_RB8ActionPerformed

    private void RB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB9ActionPerformed
       int p=0;
        boolean c=true;
        p=JOptionPane.showConfirmDialog(this,"Estas seguro que quieres dar de baja a "+ListaEmpleados.get(8).getNombre());
        if(p==0){
              c= Controlador.DarBaja(ListaEmpleados.get(8),8); 
              if(c==true){
                  JOptionPane.showMessageDialog(this,"El empleado se ha dado de baja ");
              }
            }
    }//GEN-LAST:event_RB9ActionPerformed

    private void RB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB10ActionPerformed
        int p=0;
        boolean c=true;
        p=JOptionPane.showConfirmDialog(this,"Estas seguro que quieres dar de baja a "+ListaEmpleados.get(9).getNombre());
        if(p==0){
              c= Controlador.DarBaja(ListaEmpleados.get(9),9); 
              if(c==true){
                  JOptionPane.showMessageDialog(this,"El empleado se ha dado de baja ");
              }
            }
    }//GEN-LAST:event_RB10ActionPerformed
    public void ListarEmpleados(){
        if(ListaEmpleados.size()==1){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setVisible(false);
             RB3.setVisible(false);
             RB4.setVisible(false);
             RB5.setVisible(false);
             RB6.setVisible(false);
             RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
        }
       if(ListaEmpleados.size()==2){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
              RB3.setVisible(false);
             RB4.setVisible(false);
             RB5.setVisible(false);
             RB6.setVisible(false);
             RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
        }
        if(ListaEmpleados.size()==3){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setVisible(false);
             RB5.setVisible(false);
             RB6.setVisible(false);
             RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);

        }
         if(ListaEmpleados.size()==4){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
              RB5.setVisible(false);
             RB6.setVisible(false);
             RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
         }
         if(ListaEmpleados.size()==5){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setVisible(false);
             RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
         }
         if(ListaEmpleados.size()==6){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setText(ListaEmpleados.get(5).getNombre());
                 RB7.setVisible(false);
             RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
         }
          if(ListaEmpleados.size()==7){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setText(ListaEmpleados.get(5).getNombre());
                RB7.setText(ListaEmpleados.get(6).getNombre());
                RB8.setVisible(false);
             RB9.setVisible(false);
              RB10.setVisible(false);
         }
          if(ListaEmpleados.size()==8){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setText(ListaEmpleados.get(5).getNombre());
                RB7.setText(ListaEmpleados.get(6).getNombre());
                RB8.setText(ListaEmpleados.get(7).getNombre());
                 RB9.setVisible(false);
              RB10.setVisible(false);
         }
          if(ListaEmpleados.size()==9){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setText(ListaEmpleados.get(5).getNombre());
                RB7.setText(ListaEmpleados.get(6).getNombre());
                  RB9.setText(ListaEmpleados.get(8).getNombre());
                  RB10.setVisible(false);
         }
          if(ListaEmpleados.size()==10){
             RB.setText( ListaEmpleados.get(0).getNombre());
             RB2.setText(ListaEmpleados.get(1).getNombre());
             RB3.setText(ListaEmpleados.get(2).getNombre());
             RB4.setText(ListaEmpleados.get(3).getNombre());
               RB5.setText(ListaEmpleados.get(4).getNombre());
                RB6.setText(ListaEmpleados.get(5).getNombre());
                RB7.setText(ListaEmpleados.get(6).getNombre());
                  RB9.setText(ListaEmpleados.get(8).getNombre());
                   RB10.setText(ListaEmpleados.get(9).getNombre());
         }
    
     
      
     
     
      
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VBaja dialog = new VBaja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.ButtonGroup BGempleado;
    private javax.swing.JRadioButton RB;
    private javax.swing.JRadioButton RB10;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JRadioButton RB4;
    private javax.swing.JRadioButton RB5;
    private javax.swing.JRadioButton RB6;
    private javax.swing.JRadioButton RB7;
    private javax.swing.JRadioButton RB8;
    private javax.swing.JRadioButton RB9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
