/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import practica2_p.Controlador;

/**
 *
 * @author Alaitzutzu
 */
public class Vprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Vprincipal
     */
    public Vprincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MIaltaAbogado = new javax.swing.JMenuItem();
        MIbajaAb = new javax.swing.JMenuItem();
        MimodificarAb = new javax.swing.JMenuItem();
        MiconsultaAb = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MIaltaC = new javax.swing.JMenuItem();
        MIbajaC = new javax.swing.JMenuItem();
        MImodificarC = new javax.swing.JMenuItem();
        MIconsultaC = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MIaltacj = new javax.swing.JMenuItem();
        MIbajacj = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MIsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Abogado");

        MIaltaAbogado.setText("Alta");
        MIaltaAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIaltaAbogadoActionPerformed(evt);
            }
        });
        jMenu1.add(MIaltaAbogado);

        MIbajaAb.setText("Baja");
        MIbajaAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIbajaAbActionPerformed(evt);
            }
        });
        jMenu1.add(MIbajaAb);

        MimodificarAb.setText("Modificar");
        MimodificarAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MimodificarAbActionPerformed(evt);
            }
        });
        jMenu1.add(MimodificarAb);

        MiconsultaAb.setText("Consulta");
        MiconsultaAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiconsultaAbActionPerformed(evt);
            }
        });
        jMenu1.add(MiconsultaAb);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");

        MIaltaC.setText("Alta");
        MIaltaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIaltaCActionPerformed(evt);
            }
        });
        jMenu2.add(MIaltaC);

        MIbajaC.setText("Baja");
        MIbajaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIbajaCActionPerformed(evt);
            }
        });
        jMenu2.add(MIbajaC);

        MImodificarC.setText("Modificar");
        MImodificarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MImodificarCActionPerformed(evt);
            }
        });
        jMenu2.add(MImodificarC);

        MIconsultaC.setText("Consulta");
        MIconsultaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIconsultaCActionPerformed(evt);
            }
        });
        jMenu2.add(MIconsultaC);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Casos");

        MIaltacj.setText("Alta");
        MIaltacj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIaltacjActionPerformed(evt);
            }
        });
        jMenu3.add(MIaltacj);

        MIbajacj.setText("Baja");
        MIbajacj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIbajacjActionPerformed(evt);
            }
        });
        jMenu3.add(MIbajacj);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Salir");

        MIsalir.setText("Salir");
        MIsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIsalirActionPerformed(evt);
            }
        });
        jMenu4.add(MIsalir);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MIsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIsalirActionPerformed
        Controlador.Salir();
    }//GEN-LAST:event_MIsalirActionPerformed

    private void MIaltaAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIaltaAbogadoActionPerformed
       Controlador.ValtaAbogado();
    }//GEN-LAST:event_MIaltaAbogadoActionPerformed

    private void MIbajaAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIbajaAbActionPerformed
     Controlador.VbajaAbogado();
    }//GEN-LAST:event_MIbajaAbActionPerformed

    private void MimodificarAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MimodificarAbActionPerformed
        String dni=JOptionPane.showInputDialog(this,"Introduce el dni del abogado, si no se acuerda  los abogados que tiene, introduce 'obtener datos'");
        ArrayList <String> c=new ArrayList();
        String consulta="";
        if(dni.equals("obtener datos")){
            c=Controlador.ConsultaAb();
            for(int x=0;x<c.size();x++){
                consulta+=c.get(x)+"\n";
            }
            JOptionPane.showMessageDialog(this,consulta);
        }
        else
        Controlador.VModificarAb(dni);
    }//GEN-LAST:event_MimodificarAbActionPerformed

    private void MiconsultaAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiconsultaAbActionPerformed
        Controlador.VConsultaAb();
    }//GEN-LAST:event_MiconsultaAbActionPerformed

    private void MIaltaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIaltaCActionPerformed
        Controlador.ValtaC();
    }//GEN-LAST:event_MIaltaCActionPerformed

    private void MImodificarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MImodificarCActionPerformed
       String dni=JOptionPane.showInputDialog(this,"Introduce el dni del cliente");
       Controlador.VmodificarC(dni);
    }//GEN-LAST:event_MImodificarCActionPerformed

    private void MIconsultaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIconsultaCActionPerformed
      Controlador.VconsultaC();
    }//GEN-LAST:event_MIconsultaCActionPerformed

    private void MIbajaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIbajaCActionPerformed
       Controlador.VbajaC();
    }//GEN-LAST:event_MIbajaCActionPerformed

    private void MIaltacjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIaltacjActionPerformed
      Controlador.Valtacj();
    }//GEN-LAST:event_MIaltacjActionPerformed

    private void MIbajacjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIbajacjActionPerformed
       Controlador.Vbajacj();
    }//GEN-LAST:event_MIbajacjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MIaltaAbogado;
    private javax.swing.JMenuItem MIaltaC;
    private javax.swing.JMenuItem MIaltacj;
    private javax.swing.JMenuItem MIbajaAb;
    private javax.swing.JMenuItem MIbajaC;
    private javax.swing.JMenuItem MIbajacj;
    private javax.swing.JMenuItem MIconsultaC;
    private javax.swing.JMenuItem MImodificarC;
    private javax.swing.JMenuItem MIsalir;
    private javax.swing.JMenuItem MiconsultaAb;
    private javax.swing.JMenuItem MimodificarAb;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
