/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;

/**
 *
 * @author Alaitzutzu
 */
public class Vopciones extends javax.swing.JDialog {

    /**
     * Creates new form Vopciones
     */
    public Vopciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Bdni = new javax.swing.JButton();
        Bnombre = new javax.swing.JButton();
        Bapellido = new javax.swing.JButton();
        Bdireccion = new javax.swing.JButton();
        Btelefono = new javax.swing.JButton();
        Bcorreo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Elige la opcion por la que quieres hacer la consulta");

        Bdni.setText("DNI");
        Bdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdniActionPerformed(evt);
            }
        });

        Bnombre.setText("Nombre");
        Bnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnombreActionPerformed(evt);
            }
        });

        Bapellido.setText("Apellido");
        Bapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BapellidoActionPerformed(evt);
            }
        });

        Bdireccion.setText("Direccion");
        Bdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdireccionActionPerformed(evt);
            }
        });

        Btelefono.setText("Telefono");
        Btelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtelefonoActionPerformed(evt);
            }
        });

        Bcorreo.setText("Correo");
        Bcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(Bdni)
                .addGap(60, 60, 60)
                .addComponent(Bnombre)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bcorreo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bapellido)
                        .addGap(66, 66, 66)
                        .addComponent(Bdireccion)
                        .addGap(70, 70, 70)
                        .addComponent(Btelefono)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bdni)
                    .addComponent(Bnombre)
                    .addComponent(Bapellido)
                    .addComponent(Bdireccion)
                    .addComponent(Btelefono))
                .addGap(52, 52, 52)
                .addComponent(Bcorreo)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdniActionPerformed
       Controlador.Consulta(Bdni.getName());
    }//GEN-LAST:event_BdniActionPerformed

    private void BnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnombreActionPerformed
        Controlador.Consulta(Bnombre.getName());
    }//GEN-LAST:event_BnombreActionPerformed

    private void BapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BapellidoActionPerformed
        Controlador.Consulta(Bapellido.getName());
    }//GEN-LAST:event_BapellidoActionPerformed

    private void BdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdireccionActionPerformed
       Controlador.Consulta(Bdireccion.getName());
    }//GEN-LAST:event_BdireccionActionPerformed

    private void BtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtelefonoActionPerformed
        Controlador.Consulta(Btelefono.getName());
    }//GEN-LAST:event_BtelefonoActionPerformed

    private void BcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcorreoActionPerformed
        Controlador.Consulta(Bcorreo.getName());
    }//GEN-LAST:event_BcorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vopciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vopciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vopciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vopciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Vopciones dialog = new Vopciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bapellido;
    private javax.swing.JButton Bcorreo;
    private javax.swing.JButton Bdireccion;
    private javax.swing.JButton Bdni;
    private javax.swing.JButton Bnombre;
    private javax.swing.JButton Btelefono;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
